Repository AndroidNetrunner/decrypto, pull requests merged in 2022-03, with the labels that each got.

#38 [README] 가시적으로 수정
  README.md
  yarn.lock
Labels: documentation

#40 [FIX] Fix screen to adjustable for phone
  src/Assets/img/tv-fullsz.gif
  src/Components/Common/RuleModal.tsx
  src/Layouts/BaseLayout.tsx
  src/Layouts/GameLayout.tsx
  src/Pages/Game/Components/CodeGuess.tsx
  src/Pages/Game/Components/Hints.tsx
  src/Pages/Game/Components/Word.tsx
  src/Pages/Game/index.tsx
  src/Pages/Room/index.tsx
Labels: ❣️Front

#41 Feat/socket
  package-lock.json
  package.json
  src/Interfaces/io.interface.ts
  src/Pages/Login/index.tsx
  src/Pages/Room/Components/GameStartButton.tsx
  src/Pages/Room/Components/TeamChangeButton.tsx
  src/Pages/Room/index.tsx
  src/Utils/socket.ts
  src/env.d.ts
  yarn.lock
Labels: ❣️Front, 📡Back

#44 Refactor/socket
  package-lock.json
  package.json
  src/Pages/Room/Components/TeamChangeButton.tsx
  src/Utils/firebase.ts
  src/Utils/socket.ts
  src/env.d.ts
  yarn.lock
Labels: ❣️Front, ♻️refactoring

#45 Feat/redux update
  .eslintrc.js
  package-lock.json
  package.json
  src/Interfaces/Game.interface.ts
  src/Interfaces/Room.interface.ts
  src/Interfaces/Team.interface.ts
  src/Interfaces/User.interface.ts
  src/Interfaces/io.interface.ts
  src/Pages/Game/Components/CodeGuess.tsx
  src/Pages/Game/Components/HintSubmit.tsx
  src/Pages/Game/Components/Hints.tsx
  src/Pages/Game/Components/RenderByStage.tsx
  src/Pages/Game/Components/RoundResult.tsx
  src/Pages/Game/Components/ScoreTable.tsx
  src/Pages/Game/Components/Timer.tsx
  src/Pages/Game/Components/Word.tsx
  src/Pages/Game/index.tsx
  src/Pages/Login/index.tsx
  src/Pages/Room/Components/GameStartButton.tsx
  src/Pages/Room/Components/SetGameLength.tsx
  src/Pages/Room/Components/TeamChangeButton.tsx
  src/Pages/Room/index.tsx
  src/Redux/reducer/updateDB.ts
  src/Redux/reducer/updateUser.ts
  src/Redux/store/rootStore.ts
  src/Utils/words.ts
  src/main.tsx
  vite.config.ts
  yarn.lock
Labels: ❣️Front

#46 Feat/game redux
  src/Interfaces/io.interface.ts
  src/Pages/Game/Components/CodeGuess.tsx
  src/Pages/Game/Components/Coin.tsx
  src/Pages/Game/Components/HintSubmit.tsx
  src/Pages/Game/Components/Hints.tsx
  src/Pages/Game/Components/RenderByStage.tsx
  src/Pages/Game/Components/RoundResult.tsx
  src/Pages/Game/Components/ScoreTable.tsx
  src/Pages/Game/Components/Word.tsx
  src/Pages/Game/index.tsx
  src/Pages/Room/Components/SetGameLength.tsx
  src/Pages/Room/index.tsx
Labels: ✨enhancement, ❣️Front, 📡Back

#49 [FIX] RuleModal 룰 표현 수정
  src/Components/Common/RuleModal.tsx
Labels: documentation, ❣️Front, 🐢minor

#50 Feat/waiting after submit
  package-lock.json
  src/Interfaces/io.interface.ts
  src/Pages/Game/Components/RenderByStage.tsx
  src/Pages/Game/Components/RoundResult.tsx
  yarn.lock
Labels: ✨enhancement, 🚨emergent, ❣️Front

#52 [BUG] 힌트 순서 이상한거랑 리더 안바꾸는거 수정 완료
  src/Layouts/GameLayout.tsx
  src/Pages/Game/Components/RenderByStage.tsx
  src/Pages/Game/Components/RoundResult.tsx
  src/Pages/Game/index.tsx
Labels: 🐛bug, ❣️Front

#54 [FIX] console.log 없애고 pacman 이미지파일 수정
  src/Layouts/BaseLayout.tsx
  src/Pages/Game/Components/Coin.tsx
  src/Pages/Game/Components/RenderByStage.tsx
  src/Pages/Game/Components/Timer.tsx
  src/Pages/Game/index.tsx
  src/Pages/Room/Components/GameStartButton.tsx
  src/Pages/Room/index.tsx
Labels: 🐛bug, 🐢minor

#56 [HOT FIX] 완전 개 중요한 console.log 삭제
  src/Pages/Room/index.tsx
Labels: 🚨emergent

#61 Reafactor/socket api 주소 변경
  src/Utils/socket.ts
Labels: 🐛bug, ❣️Front, 📡Back

#62 [Revert] 백엔드 연결 문제로 커밋 되돌리기
  src/Utils/socket.ts
Labels: 🚨emergent, ❣️Front, 📡Back

#63 게임화면에서 Flag 늘어나던거 수정
  src/Components/Common/Flag.tsx
  src/Pages/Game/Components/Hints.tsx
  src/Pages/Game/Components/RenderByStage.tsx
  src/Pages/Game/Components/ShowState.tsx
  src/Pages/Game/index.tsx
  src/Pages/Login/index.tsx
  src/Pages/Room/Components/SetGameLength.tsx
  src/Pages/Room/index.tsx
  src/Utils/getLeader.tsx
Labels: 🐛bug, 🔨component, ❣️Front

#71 [FIX] 두 번째 세 번째 단어에서도 1, 2, 3, 4가 출력되도록 수정
  src/Pages/Game/Components/CodeGuess.tsx
  src/Pages/Game/Components/TeamMemberList.tsx
Labels: ✨enhancement
