Repository AndroidNetrunner/decrypto, pull requests merged in 2022-02, with the labels that each got.

#3 [refactor] 로그인 페이지 라우팅, pull-request-template 적용
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/Login.tsx
  src/Pages/Game/index.tsx
  yarn.lock
Labels: ❣️Front, 🐙Github

#6 [feat] 새로운 이슈 템플릿 적용 (AndroidNetrunner-patch-1) #?
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/component.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactoring.md
Labels: documentation

#20 Feat/firebase 연동, Login Layout 작성
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/Components/Input.tsx
  src/Components/Layout/Header.tsx
  src/Components/Overlay.tsx
  src/Layouts/BaseLayout.tsx
  src/env.d.ts
  src/firebase.ts
  src/words.ts
  vite.config.ts
  yarn.lock
Labels: ❣️Front, 📡Back

#21 Timer Component 생성
  src/Pages/Game/index.tsx
  src/Pages/Game/timer.tsx
  yarn.lock
Labels: 🔨component

#22 Hints 컴포넌트, Word 컴포넌트 생성
  package-lock.json
  package.json
  src/App.tsx
  src/Components/Hints.tsx
  src/Components/Word.tsx
  src/Heading.tsx
  src/Layouts/BaseLayout.tsx
  src/Login.tsx
  yarn.lock
Labels: 🔨component

#24 🎨♻️ 코드 포메팅 정리
  package-lock.json
  src/App.tsx
  src/Components/Input.tsx
  src/Components/Word.tsx
  src/Heading.tsx
  src/Layouts/BaseLayout.tsx
  src/Login.tsx
  src/Pages/Game/timer.tsx
  src/components/HintSubmit.tsx
  src/components/OpponentHints.tsx
  src/components/ScoreTable.tsx
Labels: 🐙Github, ♻️refactoring

#25 Feat/TeamChangeButton #4
  src/Pages/Game/Components/TeamChangeButton.tsx
  src/Pages/Game/index.tsx
Labels: 🔨component

#27 fix/Issue Template Develop 반영
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/component.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactoring.md
Labels: 🚨emergent, 🐙Github

#30 Feat/tooltip #29
  src/Components/Common/Tooltip.tsx
Labels: 🔨component

#31 [DOCUMENT] rulebook.md
  package-lock.json
  rulebook.md
Labels: documentation

#36 Feat/login page
  README.md
  public/img/book-close.png
  public/img/book-open.png
  public/img/my-coin-green.gif
  public/img/my-coin-pink.gif
  public/img/pacman.gif
  public/img/tv (1).gif
  src/App.tsx
  src/Components/Common/RuleModal.tsx
  src/Components/Layout/Header.tsx
  src/Layouts/BaseLayout.tsx
  src/Layouts/GameLayout.tsx
  src/Pages/Game/index.tsx
  src/Pages/Login/index.tsx
  src/Pages/Room/index.tsx
  src/Styles/GlobalStyle.ts
  src/Utils/firebase.ts
  src/Utils/words.ts
Labels: 🔨component, ❣️Front, ♻️refactoring

#37 Feat/code guess
  src/Pages/Game/Components/CodeGuess.tsx
  src/Styles/GlobalStyle.ts
  yarn.lock
Labels: 🔨component
